language: python
sudo: false

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "nightly"

matrix:
  allow_failures:
      - python: "3.7-dev"
      - python: "3.8-dev"
      - python: "nightly"

virtualenv:
  system_site_packages: false

services:
  - postgresql

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y openssl build-essential xorg libssl-dev xfonts-75dpi ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -xvf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo mv wkhtmltox/bin/wkhtmltopdf /usr/bin/wkhtmltopdf ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -rf wkhtmltox ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm wkhtmltox-0.12.4_linux-generic-amd64.tar.xz ; fi

install:
  - pip install psycopg2
  - pip install anyblok
  - pip install -U flake8 coverage pytest pytest-cov
  - pip install coveralls
  - pip install .

env:
  global:
    - ANYBLOK_DATABASE_NAME=travis_ci_test
    - ANYBLOK_DATABASE_DRIVER=postgresql
    - ANYBLOK_DATABASE_USER=postgres
  matrix:
    - BLOKS=attachment report wkhtml2pdf report-format
    - BLOKS=attachment report wkhtml2pdf report-format anyblok-postgres

script:
  - flake8 anyblok_attachment
  - psql -c 'create database travis_ci_test;' -U postgres
  - pytest  --cov-report= --cov=anyblok_attachment  anyblok_attachment/tests
  - psql -c 'drop database travis_ci_test;' -U postgres
  - anyblok_createdb --install-bloks $BLOKS
  - pytest --cov-report= --cov=anyblok_attachment anyblok_attachment/bloks
  
after_success:
  coveralls --data_file=.coverage --config_file=.coveragerc
